### ISSUE TITLE
updating xBRZ to latest?

### ISSUE THREAD

**Issue by AquariusPower** [atheros/xbrzscale#11]
As I read, this seems to be the differences from the work here:

```
xBRZ 1.6 [2018-02-27]
---------------------
Added bilinear scaling
Updated license info
Option to skip color buffer creation


xBRZ 1.5 [2017-08-07]
---------------------
Added RGB conversion routines
```

It doesnt look as having had a performance improvement (probably here we have with the cache), I will take a look at the code tho. 

May be that 'bilinear scaling' has something interesting. I tried reading some of the code, not used to it tho, my guess the result will be not the same quality of the main scaling, not sure tho.

The goal in Ivan is just to UP scale, and it seems performance may be better if the code only does that?

anyway, do you believe it is worth updating here with 1.6?

**Comment by BradleyPudge** [comment]
[License - Copy.txt](https://github.com/atheros/xbrzscale/files/2717637/License.-.Copy.txt)
[License.txt](https://github.com/atheros/xbrzscale/files/2717638/License.txt)







[Changelog - Copy.txt](https://github.com/atheros/xbrzscale/files/2717639/Changelog.-.Copy.txt)
[Changelog.txt](https://github.com/atheros/xbrzscale/files/2717640/Changelog.txt)

**Comment by AquariusPower** [comment]
@BradleyPudge  some words explaining what did you mean would help :)

**Comment by PeterBBBBB** [comment]
Please also add release tags, so versioned tarballs can be extracted.
For 1.8, need to use -std=c++17  in the makefile.

**Comment by atheros** [comment]
Updated to 1.8
