### ISSUE TITLE
Error on compile

### ISSUE THREAD

**Issue by guspolly** [atheros/xbrzscale#2]
I'm not a coder, sorry if this seems self-evident. This is the output of make:

g++ -std=c++0x -c -o xbrzscale.o xbrzscale.cpp `sdl-config --cflags`
xbrzscale.cpp: In function ‘int main(int, char**)’:
xbrzscale.cpp:193:57: error: too few arguments to function ‘void xbrz::scale(size_t, const uint32_t*, uint32_t*, int, int, xbrz::ColorFormat, const xbrz::ScalerCfg&, int, int)’
  xbrz::scale(scale, in_data, dest, src_width, src_height);
                                                         ^
In file included from xbrzscale.cpp:26:0:
xbrz/xbrz.h:57:6: note: declared here
 void scale(size_t factor, //valid range: 2 - 5
      ^
make: *** [xbrzscale.o] Error 1

**Comment by atheros** [comment]
I cannot reproduce this problem
